name = "Havoc Beyond the Clouds"
author = "minecraftbossdj, NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24e22147dcb90fae380e409a894c2ee254050fc1d06536dcdea4ba8a4170fbde"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
